### ISSUE TITLE
question about postprocess

### ISSUE THREAD

**Issue by buptwxl** [LibRaw/LibRaw-demosaic-pack-GPL2#2]
Sorry to bother you, while i have a problem about the  postprocess order . We are doing a project about low-light images and I find many authors using rawpy (postprocess), now we try to process the rgb image back to its  original raw. I only get information of postprocess parameters without its real operations and I don't find its definition file.
 Maybe I used a wrong way to address this problem. so i wonder if you can help me ? the postprocess definition file or its real steps to process raw (like demosaic , white balance or some others) Thank you very much.

**Comment by LibRaw** [comment]
I'm not sure that I understood your task correctly

Rawpy uses LibRaw (AFAIK).
LibRaw postprocessing code is 'very well documented in C++', you may start your investigation here: https://github.com/LibRaw/LibRaw/blob/master/src/libraw_cxx.cpp#L4755
